INSERT [dbo].[Groups] ([Name]) VALUES (N'IP-32')
INSERT [dbo].[Groups] ([Name]) VALUES (N'IP-21')
INSERT [dbo].[Groups] ([Name]) VALUES (N'IP-31')
INSERT [dbo].[Groups] ([Name]) VALUES (N'ITP-12')
INSERT [dbo].[Groups] ([Name]) VALUES (N'ITI-22')
INSERT [dbo].[Groups] ([Name]) VALUES (N'ITP-21')
INSERT [dbo].[Groups] ([Name]) VALUES (N'IP-41')
INSERT [dbo].[Groups] ([Name]) VALUES (N'ITI-31')
INSERT [dbo].[Groups] ([Name]) VALUES (N'ITP32')
INSERT [dbo].[Groups] ([Name]) VALUES (N'IP-11')
INSERT [dbo].[Groups] ([Name]) VALUES (N'IS-21')
INSERT [dbo].[Groups] ([Name]) VALUES (N'IS-22')
INSERT [dbo].[Groups] ([Name]) VALUES (N'IS-11')
INSERT [dbo].[Groups] ([Name]) VALUES (N'IS-12')


INSERT [dbo].[Sessions] ([GroupId], [SessionNumber]) VALUES (1, 1)
INSERT [dbo].[Sessions] ([GroupId], [SessionNumber]) VALUES (2, 2)
INSERT [dbo].[Sessions] ([GroupId], [SessionNumber]) VALUES (3, 3)
INSERT [dbo].[Sessions] ([GroupId], [SessionNumber]) VALUES (4, 4)
INSERT [dbo].[Sessions] ([GroupId], [SessionNumber]) VALUES (1, 2)
INSERT [dbo].[Sessions] ([GroupId], [SessionNumber]) VALUES (2, 3)
INSERT [dbo].[Sessions] ([GroupId], [SessionNumber]) VALUES (3, 4)
INSERT [dbo].[Sessions] ([GroupId], [SessionNumber]) VALUES (4, 4)


INSERT [dbo].[Students] ([FullName], [Gender], [DateOfBirth], [GroupId]) VALUES (N'Shyshkavets Pavel Sergeevich', N'Male', CAST(N'2000-05-09' AS Date), 1)
INSERT [dbo].[Students] ([FullName], [Gender], [DateOfBirth], [GroupId]) VALUES (N'Reita Match Sergeevna', N'Woman', CAST(N'2001-06-11' AS Date), 1)
INSERT [dbo].[Students] ([FullName], [Gender], [DateOfBirth], [GroupId]) VALUES (N'Artem Lukavtsov Gennadevich', N'Male', CAST(N'2000-02-13' AS Date), 2)
INSERT [dbo].[Students] ([FullName], [Gender], [DateOfBirth], [GroupId]) VALUES (N'Borisenko Ivan Sergeevich', N'Male', CAST(N'2002-08-19' AS Date), 2)
INSERT [dbo].[Students] ([FullName], [Gender], [DateOfBirth], [GroupId]) VALUES (N'Chaykov Andey Vasllyevich', N'Male', CAST(N'2003-03-03' AS Date), 3)
INSERT [dbo].[Students] ([FullName], [Gender], [DateOfBirth], [GroupId]) VALUES (N'Palatkin Daniil Aleksandrovich', N'Male', CAST(N'2000-09-21' AS Date), 3)
INSERT [dbo].[Students] ([FullName], [Gender], [DateOfBirth], [GroupId]) VALUES (N'Pankova Anastasiya Evgenevna', N'Woman', CAST(N'2001-01-01' AS Date), 4)
INSERT [dbo].[Students] ([FullName], [Gender], [DateOfBirth], [GroupId]) VALUES (N'Gruzdov Pavel Genadevich', N'Male', CAST(N'2002-03-26' AS Date), 4)
INSERT [dbo].[Students] ([FullName], [Gender], [DateOfBirth], [GroupId]) VALUES (N'Galavneva Ekaterina Genadevna', N'Woman', CAST(N'2000-06-19' AS Date), 5)
INSERT [dbo].[Students] ([FullName], [Gender], [DateOfBirth], [GroupId]) VALUES (N'Saykov Anatoliy Sergeevich', N'Male', CAST(N'2001-09-13' AS Date), 5)


INSERT [dbo].[EducationalSubjects] ([SubjectName], [SubjectType]) VALUES (N'OOP', N'Exam')
INSERT [dbo].[EducationalSubjects] ([SubjectName], [SubjectType]) VALUES (N'OOP', N'Credit')
INSERT [dbo].[EducationalSubjects] ([SubjectName], [SubjectType]) VALUES (N'Math', N'Exam')
INSERT [dbo].[EducationalSubjects] ([SubjectName], [SubjectType]) VALUES (N'History', N'Credit')
INSERT [dbo].[EducationalSubjects] ([SubjectName], [SubjectType]) VALUES (N'SUBD', N'Exam')
INSERT [dbo].[EducationalSubjects] ([SubjectName], [SubjectType]) VALUES (N'TVIMS', N'Exam')
INSERT [dbo].[EducationalSubjects] ([SubjectName], [SubjectType]) VALUES (N'SMAZAR', N'Exam')
INSERT [dbo].[EducationalSubjects] ([SubjectName], [SubjectType]) VALUES (N'Math', N'Credit')
INSERT [dbo].[EducationalSubjects] ([SubjectName], [SubjectType]) VALUES (N'MCHA', N'Exam')


INSERT [dbo].[SessionEducationalSubjects] ([SessionId], [EducationalSubjectId], [Date]) VALUES (1, 1, CAST(N'2020-06-19' AS Date))
INSERT [dbo].[SessionEducationalSubjects] ([SessionId], [EducationalSubjectId], [Date]) VALUES (1, 2, CAST(N'2020-06-21' AS Date))
INSERT [dbo].[SessionEducationalSubjects] ([SessionId], [EducationalSubjectId], [Date]) VALUES (2, 3, CAST(N'2020-06-15' AS Date))
INSERT [dbo].[SessionEducationalSubjects] ([SessionId], [EducationalSubjectId], [Date]) VALUES (2, 4, CAST(N'2020-05-19' AS Date))
INSERT [dbo].[SessionEducationalSubjects] ([SessionId], [EducationalSubjectId], [Date]) VALUES (3, 5, CAST(N'2020-09-11' AS Date))
INSERT [dbo].[SessionEducationalSubjects] ([SessionId], [EducationalSubjectId], [Date]) VALUES (3, 6, CAST(N'2020-08-17' AS Date))
INSERT [dbo].[SessionEducationalSubjects] ([SessionId], [EducationalSubjectId], [Date]) VALUES (4, 7, CAST(N'2020-05-19' AS Date))
INSERT [dbo].[SessionEducationalSubjects] ([SessionId], [EducationalSubjectId], [Date]) VALUES (4, 7, CAST(N'2020-05-05' AS Date))
INSERT [dbo].[SessionEducationalSubjects] ([SessionId], [EducationalSubjectId], [Date]) VALUES (5, 8, CAST(N'2020-11-09' AS Date))
INSERT [dbo].[SessionEducationalSubjects] ([SessionId], [EducationalSubjectId], [Date]) VALUES (5, 8, CAST(N'2020-09-05' AS Date))
INSERT [dbo].[SessionEducationalSubjects] ([SessionId], [EducationalSubjectId], [Date]) VALUES (6, 9, CAST(N'2020-09-06' AS Date))
INSERT [dbo].[SessionEducationalSubjects] ([SessionId], [EducationalSubjectId], [Date]) VALUES (6, 9, CAST(N'2020-07-07' AS Date))


INSERT [dbo].[StudentResults] ([StudentId], [SessionEducationalSubjectId], [Mark]) VALUES (1, 1, N'8')
INSERT [dbo].[StudentResults] ([StudentId], [SessionEducationalSubjectId], [Mark]) VALUES (1, 2, N'Passed')
INSERT [dbo].[StudentResults] ([StudentId], [SessionEducationalSubjectId], [Mark]) VALUES (2, 1, N'3')
INSERT [dbo].[StudentResults] ([StudentId], [SessionEducationalSubjectId], [Mark]) VALUES (2, 2, N'Not Passes')
INSERT [dbo].[StudentResults] ([StudentId], [SessionEducationalSubjectId], [Mark]) VALUES (3, 3, N'2')
INSERT [dbo].[StudentResults] ([StudentId], [SessionEducationalSubjectId], [Mark]) VALUES (3, 4, N'Passed')
INSERT [dbo].[StudentResults] ([StudentId], [SessionEducationalSubjectId], [Mark]) VALUES (4, 3, N'10')
INSERT [dbo].[StudentResults] ([StudentId], [SessionEducationalSubjectId], [Mark]) VALUES (4, 4, N'Not Passed')
INSERT [dbo].[StudentResults] ([StudentId], [SessionEducationalSubjectId], [Mark]) VALUES (5, 5, N'5')
INSERT [dbo].[StudentResults] ([StudentId], [SessionEducationalSubjectId], [Mark]) VALUES (5, 6, N'9')
INSERT [dbo].[StudentResults] ([StudentId], [SessionEducationalSubjectId], [Mark]) VALUES (6, 5, N'7')
INSERT [dbo].[StudentResults] ([StudentId], [SessionEducationalSubjectId], [Mark]) VALUES (6, 6, N'2')